import React, { forwardRef } from 'react';

interface PrintableDocumentProps {
  doc: {
    type: string;
    content: string;
    date: string;
  };
}

const PrintableDocument = forwardRef<HTMLDivElement, PrintableDocumentProps>(({ doc }, ref) => {
  const formattedDate = new Date(doc.date).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div
      ref={ref}
      className="print-container"
      style={{
        fontFamily: 'Arial, sans-serif',
        padding: '2rem',
        color: '#000',
        position: 'relative',
      }}
    >
      {/* Header */}
      <div
        className="print-header"
        style={{
          display: 'flex',
          alignItems: 'center',
          borderBottom: '2px solid #ccc',
          paddingBottom: '10px',
          marginBottom: '20px',
        }}
      >
        <img src="/logo.png" alt="Logo" style={{ width: '60px', marginRight: '15px' }} />
        <h1 style={{ fontSize: '24px', fontWeight: 'bold', margin: 0 }}>AI Legal Assistant</h1>
      </div>

      {/* Watermark */}
      <div
        className="print-watermark"
        style={{
          position: 'absolute',
          top: '40%',
          left: '30%',
          fontSize: '36px',
          color: '#dddddd',
          transform: 'rotate(-30deg)',
          zIndex: 0,
          userSelect: 'none',
          pointerEvents: 'none',
          opacity: 0.5,  // To ensure watermark is visible in print
        }}
      >
        Generated by AI Legal Assistant
      </div>

      {/* Document Content */}
      <div style={{ position: 'relative', zIndex: 1 }}>
        <h2 style={{ fontSize: '20px', marginBottom: '0.5rem' }}>{doc.type}</h2>
        <p style={{ fontSize: '14px', color: '#444' }}><strong>Date:</strong> {formattedDate}</p>
        <hr style={{ margin: '1rem 0', borderColor: '#ccc' }} />
        <div
          style={{
            whiteSpace: 'pre-wrap',
            fontSize: '16px',
            wordWrap: 'break-word',
            textAlign: 'justify',
          }}
        >
          {doc.content}
        </div>
      </div>

      {/* Footer with Page Number (via CSS counter) */}
      <style>
        {`
          @media print {
            html, body {
              height: auto !important;
              overflow: visible !important;
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
              background: #fff !important;
            }

            @page {
              size: A4;
              margin: 20mm;
              counter-increment: page;
            }

            .print-container {
              position: relative;
            }

            .print-footer::after {
              content: "Page " counter(page);
              position: fixed;
              bottom: 10mm;
              left: 0;
              right: 0;
              text-align: center;
              font-size: 12px;
              color: #666;
            }

            .print-watermark {
              display: block;
            }

            .print-header {
              position: fixed;
              top: 0;
              left: 0;
              right: 0;
              padding: 1rem 2rem;
              background: white;
              border-bottom: 1px solid #ccc;
              z-index: 10;
            }

            .print-header img {
              max-height: 50px;
            }

            body {
              counter-reset: page;
            }
          }
        `}
      </style>

      <div className="print-footer" />
    </div>
  );
});

export default PrintableDocument;
